
spring:
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: jdbc:mariadb://localhost:3307/um-para-muitos4
    username: sa
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true

server:
  servlet:
    context-path: /api

logging:
  level:
    '[br.com.zup.handora]': debug

## Running MariaDB container:
#
#  docker run --detach --name mariadb-um-para-muitos4 --env MARIADB_USER=sa --env MARIADB_PASSWORD=password --env MARIADB_ROOT_PASSWORD=rootpassword --env MARIADB_DATABASE=um-para-muitos4 -p 3307:3306 mariadb:latest
